var fs = require("fs");
var a = [];
a.push('export interface ScoreResult{hook:number;emotion:number;novelty:number;information:number;curiosity:number;payoff:number;coherence:number;overall:number;reasons:string[]}');
a.push('export interface NarrativeArc{hasArc:boolean;strength:number;phases:string[]}');
a.push('');
a.push('export function scoreText(text:string):ScoreResult{');
a.push('  const hook=clamp(sHook(text)*100),emotion=clamp(sEmotion(text)*100),novelty=clamp(sNovelty(text)*100);');
a.push('  const information=clamp(sInfo(text)*100),curiosity=clamp(sCuriosity(text)*100);');
a.push('  const payoff=clamp(sPayoff(text)*100),coherence=clamp(sCoherence(text)*100);');
a.push('  const overall=hook*.20+emotion*.15+novelty*.15+information*.15+curiosity*.10+payoff*.15+coherence*.10;');
a.push('  return{hook,emotion,novelty,information,curiosity,payoff,coherence,overall,reasons:bR(hook,emotion,novelty,curiosity,payoff,coherence,text)}');
a.push('}');
a.push('');
a.push('export function detectNarrativeArc(text:string):NarrativeArc{');
a.push('  const p:string[]=[];let s=0;');
a.push('  if(NM_PAT.test(text)){p.push("setup");s+=.2}');
a.push('  if(ES_PAT.test(text)||/\\b(scared|fail|struggle|quit)\\b/i.test(text)){p.push("tension");s+=.3}');
a.push('  if(CON_PAT.test(text)){p.push("turn");s+=.25}');
a.push('  if(PAY_PAT.test(text)){p.push("payoff");s+=.25}');
a.push('  if(p.length>=3)s+=.1;');
a.push('  return{hasArc:p.length>=2,strength:Math.min(1,s),phases:p}');
a.push('}');
fs.appendFileSync("e:/video/packages/ai/src/providers/signals.ts", a.join("\n") + "\n");
console.log("part2:", a.length);
