var fs = require("fs");
var lines = [];
lines.push('import Link from "next/link";');
lines.push('');
lines.push('export default function StudioPage() {');
lines.push('  const clips = [');
lines.push('    { rank: 1, score: 46, title: "Adoption story with emotional arc", style: "cinematic", engagement: 78, quality: 82, effects: 2 },');
lines.push('    { rank: 2, score: 36, title: "College adoption detail", style: "podcast", engagement: 71, quality: 75, effects: 1 },');
lines.push('    { rank: 3, score: 35, title: "Three stories hook", style: "hype", engagement: 85, quality: 79, effects: 3 },');
lines.push('    { rank: 4, score: 34, title: "Commencement opening", style: "podcast", engagement: 68, quality: 72, effects: 1 },');
lines.push('    { rank: 5, score: 32, title: "Adoption setup", style: "documentary", engagement: 65, quality: 80, effects: 0 },');
lines.push('    { rank: 6, score: 29, title: "Reed College dropout", style: "educational", engagement: 62, quality: 74, effects: 1 },');
lines.push('  ];');
lines.push('  return (');
lines.push('    <div className="flex flex-1">');
lines.push('      <aside className="hidden w-64 flex-col border-r border-zinc-800 bg-zinc-900/50 p-4 lg:flex">');
lines.push('        <div className="mb-8 flex items-center gap-2 px-2">');
lines.push('          <div className="h-8 w-8 rounded-lg bg-indigo-600 flex items-center justify-center text-sm font-bold">CF</div>');
lines.push('          <span className="text-lg font-semibold text-white">ClipForge Studio</span>');
lines.push('        </div>');
lines.push('        <nav className="flex flex-col gap-1">');
lines.push('          <Link href="/dashboard" className="rounded-lg px-3 py-2 text-sm text-zinc-500 hover:bg-zinc-800">Dashboard</Link>');
lines.push('          <Link href="/studio" className="rounded-lg bg-zinc-800 px-3 py-2 text-sm font-medium text-white">Studio</Link>');
lines.push('        </nav>');
lines.push('      </aside>');
lines.push('      <main className="flex-1 overflow-y-auto">');
lines.push('        <div className="border-b border-zinc-800 px-8 py-4">');
lines.push('          <h1 className="text-xl font-bold text-white">Steve Jobs Stanford — 6 Clips</h1>');
lines.push('          <p className="mt-1 text-sm text-zinc-500">3 min source · 6 clips · All validated</p>');
lines.push('        </div>');
lines.push('        <div className="p-8">');
lines.push('          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">');
lines.push('            {clips.map(c => (');
lines.push('              <div key={c.rank} className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-4">');
lines.push('                <div className="mb-2 flex items-center justify-between">');
lines.push('                  <span className="text-xs font-semibold text-zinc-500">#{c.rank}</span>');
lines.push('                  <span className="rounded-full bg-indigo-500/10 px-2 py-0.5 text-xs text-indigo-400">{c.style}</span>');
lines.push('                </div>');
lines.push('                <div className="mb-3 flex aspect-video items-center justify-center rounded-lg bg-zinc-800 text-2xl">🎬</div>');
lines.push('                <h3 className="text-sm font-medium text-white">{c.title}</h3>');
lines.push('                <div className="mt-3 grid grid-cols-2 gap-2 text-xs">');
lines.push('                  <div><span className="text-zinc-500">Engagement</span><div className="mt-1 h-1.5 rounded-full bg-zinc-800"><div className="h-full rounded-full bg-emerald-500" style={{width:`${c.engagement}%`}} /></div></div>');
lines.push('                  <div><span className="text-zinc-500">Quality</span><div className="mt-1 h-1.5 rounded-full bg-zinc-800"><div className="h-full rounded-full bg-blue-500" style={{width:`${c.quality}%`}} /></div></div>');
lines.push('                </div>');
lines.push('                <div className="mt-3 flex gap-2">');
lines.push('                  <button className="flex-1 rounded bg-zinc-800 px-2 py-1 text-xs text-zinc-300">Edit Plan</button>');
lines.push('                  <button className="flex-1 rounded bg-zinc-800 px-2 py-1 text-xs text-zinc-300">Preview</button>');
lines.push('                  <button className="flex-1 rounded bg-zinc-800 px-2 py-1 text-xs text-zinc-300">Export</button>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            ))}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      </main>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');
fs.writeFileSync("e:/video/apps/web/app/studio/page.tsx", lines.join("\n") + "\n", "utf-8");
console.log("Wrote studio page:", lines.length, "lines");
